#!/bin/bash -l
# activate the environment
eval "$(conda shell.bash hook)"
conda activate pfp_env
# wait until the command has completed
wait
# check the command line arguments
if [ "$1" != "batch" ]; then
    # run interactive if anything other than batch entered on command line
    python PyFluxPro.py
else
    # check to see if control file entered on command line
    if [ "$2" != "" ]; then
        # run batch with specified control file
        python batch.py $2
    else
        # run batch with no control file
        python batch.py
    fi
fi
